services:
  postgres-categorias:
    image: postgres:16
    container_name: postgres-categorias
    restart: always
    environment:
      POSTGRES_DB: categorias_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5434:5432"
    volumes:
      - postgres_categorias_data:/var/lib/postgresql/data

  postgres-usuarios:
    image: postgres:16
    container_name: postgres-usuarios
    restart: always
    environment:
      POSTGRES_DB: usuario_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports: 
    - "5435:5432"
    volumes:
    - postgres_categorias_data:/var/lib/postgresql/data
    

  postgres-productos:
    image: postgres:16
    container_name: postgres-productos
    restart: always
    environment:
      POSTGRES_DB: productos_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"
    volumes:
      - postgres_productos_data:/var/lib/postgresql/data

  postgres-inventario:
    image: postgres:16
    container_name: postgres-inventario
    restart: always
    environment:
      POSTGRES_DB: inventario_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5440:5432"
    volumes:
      - postgres_inventario_data:/var/lib/postgresql/data

  postgres-clientes:
    image: postgres:16
    container_name: postgres-clientes
    restart: always
    environment:
      POSTGRES_DB: clientes_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5437:5432"
    volumes:
      - postgres_clientes_data:/var/lib/postgresql/data

  postgres-ventas:
    image: postgres:16
    container_name: postgres-ventas
    restart: always
    environment:
      POSTGRES_DB: ventas_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5438:5432"
    volumes:
      - postgres_ventas_data:/var/lib/postgresql/data

  postgres-detalle-venta:
    image: postgres:16
    container_name: postgres-detalle-venta
    restart: always
    environment:
      POSTGRES_DB: detalle_venta_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5439:5432"
    volumes:
      - postgres_detalle_venta_data:/var/lib/postgresql/data

  categorias-service:
    build:
      context: ./categorias-service
    container_name: categorias-service
    restart: always
    depends_on:
      - postgres-categorias
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-categorias:5432/categorias_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123

  usuarios-service:
    build:
      context: ./usuarios-service
    container_name: usuarios-service
    restart: always
    depends_on:
      - postgres-usuarios
    ports:
      - "8093:8093"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-productos:5432/usuarios_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      CATEGORIA_SERVICE_URL: http://categorias-service:8084/api/v1/usuarios


  productos-service:
    build:
      context: ./productos-service
    container_name: productos-service
    restart: always
    depends_on:
      - postgres-productos
      - categorias-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-productos:5432/productos_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      CATEGORIA_SERVICE_URL: http://categorias-service:8084/api/v1/categorias

  inventario-service:
    build:
      context: ./inventario-service
    container_name: inventario-service
    restart: always
    depends_on:
      - postgres-inventario
      - productos-service
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-inventario:5432/inventario_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      PRODUCTO_SERVICE_URL: http://productos-service:8085/api/v1/productos

  clientes-service:
    build:
      context: ./clientes-service
    container_name: clientes-service
    restart: always
    depends_on:
      - postgres-clientes
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-clientes:5432/clientes_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123

  ventas-service:
    build:
      context: ./ventas-service
    container_name: ventas-service
    restart: always
    depends_on:
      - postgres-ventas
      - clientes-service
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-ventas:5432/ventas_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      CLIENTES_SERVICE_URL: http://clientes-service:8087/api/v1/clientes
      DETALLEVENTAS_SERVICE_URL: http://detalle-venta-service:8089/api/v1/detalles

  detalle-venta-service:
    build:
      context: ./DetalleVentas-service
    container_name: detalle-venta-service
    restart: always
    depends_on:
      - postgres-detalle-venta
      - productos-service
      - ventas-service
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-detalle-venta:5432/detalle_venta_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      PRODUCTO_SERVICE_URL: http://productos-service:8085/api/v1/productos
      VENTA_SERVICE_URL: http://ventas-service:8088/api/v1/ventas


volumes:
  postgres_categorias_data:
  postgres_productos_data:
  postgres_inventario_data:
  postgres_clientes_data:
  postgres_ventas_data:
  postgres_detalle_venta_data:
  postgres_usuarios_data: