services:

  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    restart: always
    depends_on:
      - eureka-server
    ports:
      - "8083:8083"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  postgres-categorias:
    image: postgres:16
    container_name: postgres-categorias
    restart: always
    environment:
      POSTGRES_DB: categorias_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5434:5432"
    volumes:
      - postgres_categorias_data:/var/lib/postgresql/data

  postgres-categorias-test:
    image: postgres:16
    container_name: postgres-categorias-test
    restart: always
    environment:
      POSTGRES_DB: categorias_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5454:5432"
    volumes:
      - postgres_categorias_test_data:/var/lib/postgresql/data  

  postgres-productos:
    image: postgres:16
    container_name: postgres-productos
    restart: always
    environment:
      POSTGRES_DB: productos_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"
    volumes:
      - postgres_productos_data:/var/lib/postgresql/data

  postgres-productos-test:
    image: postgres:16
    container_name: postgres-productos-test
    restart: always
    environment:
      POSTGRES_DB: productos_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5460:5432"
    volumes:
      - postgres_productos_test_data:/var/lib/postgresql/data

  postgres-inventario:
    image: postgres:16
    container_name: postgres-inventario
    restart: always
    environment:
      POSTGRES_DB: inventario_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5440:5432"
    volumes:
      - postgres_inventario_data:/var/lib/postgresql/data

  postgres-inventario-test:
    image: postgres:16
    container_name: postgres-inventario-test
    restart: always
    environment:
      POSTGRES_DB: inventario_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5458:5432"
    volumes:
      - postgres_inventario_test_data:/var/lib/postgresql/data

  postgres-clientes:
    image: postgres:16
    container_name: postgres-clientes
    restart: always
    environment:
      POSTGRES_DB: clientes_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5437:5432"
    volumes:
      - postgres_clientes_data:/var/lib/postgresql/data

  postgres-clientes-test:
    image: postgres:16
    container_name: postgres-clientes-test
    restart: always
    environment:
      POSTGRES_DB: clientes_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5455:5432"
    volumes:
      - postgres_clientes_test_data:/var/lib/postgresql/data

  postgres-ventas:
    image: postgres:16
    container_name: postgres-ventas
    restart: always
    environment:
      POSTGRES_DB: ventas_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5438:5432"
    volumes:
      - postgres_ventas_data:/var/lib/postgresql/data
  
  postgres-ventas-test:
    image: postgres:16
    container_name: postgres-ventas-test
    restart: always
    environment:
      POSTGRES_DB: ventas_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5463:5432"
    volumes:
      - postgres_ventas_test_data:/var/lib/postgresql/data

  postgres-detalle-venta:
    image: postgres:16
    container_name: postgres-detalle-venta
    restart: always
    environment:
      POSTGRES_DB: detalle_venta_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5439:5432"
    volumes:
      - postgres_detalle_venta_data:/var/lib/postgresql/data

  postgres-proveedores:
    image: postgres:16
    container_name: postgres-proveedores
    restart: always
    environment:
      POSTGRES_DB: proveedores_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5441:5432"
    volumes:
      - postgres_proveedores_data:/var/lib/postgresql/data

  postgres-proveedores-test:
    image: postgres:16
    container_name: postgres-proveedores-test
    restart: always
    environment:
      POSTGRES_DB: proveedores_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5461:5432"
    volumes:
      - postgres_proveedores_test_data:/var/lib/postgresql/data

  postgres-empleados:
    image: postgres:16
    container_name: postgres-empleados
    restart: always
    environment:
      POSTGRES_DB: empleados_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5442:5432"
    volumes:
      - postgres_empleados_data:/var/lib/postgresql/data

  postgres-empleados-test:
    image: postgres:16
    container_name: postgres-empleados-test
    restart: always
    environment:
      POSTGRES_DB: empleados_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5457:5432"
    volumes:
      - postgres_empleados_test_data:/var/lib/postgresql/data

  postgres-pedidos:
    image: postgres:16
    container_name: postgres-pedidos
    restart: always
    environment:
      POSTGRES_DB: pedidos_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5443:5432"
    volumes:
      - postgres_pedidos_data:/var/lib/postgresql/data

  postgres-pedidos-test:
    image: postgres:16
    container_name: postgres-pedidos-test
    restart: always
    environment:
      POSTGRES_DB: pedidos_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5459:5432"
    volumes:
      - postgres_pedidos_test_data:/var/lib/postgresql/data

  postgres-usuarios:
    image: postgres:16
    container_name: postgres-usuarios
    restart: always
    environment:
      POSTGRES_DB: usuarios_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5444:5432"
    volumes:
      - postgres_usuarios_data:/var/lib/postgresql/data
  
  postgres-usuarios-test:
    image: postgres:16
    container_name: postgres-usuarios-test
    restart: always
    environment:
      POSTGRES_DB: usuarios_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5462:5432"
    volumes:
      - postgres_usuarios_test_data:/var/lib/postgresql/data

  usuarios-service:
    build:
      context: ./usuarios-service
    container_name: usuarios-service
    restart: always
    depends_on:
      - postgres-usuarios
      - eureka-server
    ports:
      - "8093:8093"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-usuarios:5432/usuarios_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  categorias-service:
    build:
      context: ./categorias-service
    container_name: categorias-service
    restart: always
    depends_on:
      - postgres-categorias
      - eureka-server
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-categorias:5432/categorias_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  productos-service:
    build:
      context: ./productos-service
    container_name: productos-service
    restart: always
    depends_on:
      - postgres-productos
      - categorias-service
      - inventario-service
      - proveedores-service
      - eureka-server
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-productos:5432/productos_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      CATEGORIA_SERVICE_URL: http://categorias-service:8084
      INVENTARIO_SERVICE_URL: http://inventario-service:8090
      PROVEEDOR_SERVICE_URL: http://proveedores-service:8086
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  inventario-service:
    build:
      context: ./inventario-service
    container_name: inventario-service
    restart: always
    depends_on:
      - postgres-inventario
      - eureka-server
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-inventario:5432/inventario_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      PRODUCTO_SERVICE_URL: http://productos-service:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  proveedores-service:
    build:
      context: ./proveedores-service
    container_name: proveedores-service
    restart: always
    depends_on:
      - postgres-proveedores
      - eureka-server
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-proveedores:5432/proveedores_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      PRODUCTO_SERVICE_URL: http://productos-service:8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  clientes-service:
    build:
      context: ./clientes-service
    container_name: clientes-service
    restart: always
    depends_on:
      - postgres-clientes
      - eureka-server
    ports:
      - "8087:8087"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-clientes:5432/clientes_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      PEDIDO_SERVICE_URL: http://pedidos-service:8092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  empleados-service:
    build:
      context: ./empleados-service
    container_name: empleados-service
    restart: always
    depends_on:
      - postgres-empleados
      - eureka-server
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-empleados:5432/empleados_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      VENTA_SERVICE_URL: http://ventas-service:8088
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  ventas-service:
    build:
      context: ./ventas-service
    container_name: ventas-service
    restart: always
    depends_on:
      - postgres-ventas
      - clientes-service
      - empleados-service
      - eureka-server
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-ventas:5432/ventas_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      CLIENTE_SERVICE_URL: http://clientes-service:8087
      DETALLEVENTAS_SERVICE_URL: http://detalle-venta-service:8089
      EMPLEADO_SERVICE_URL: http://empleados-service:8091
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  detalle-venta-service:
    build:
      context: ./DetalleVentas-service
    container_name: detalle-venta-service
    restart: always
    depends_on:
      - postgres-detalle-venta
      - inventario-service
      - productos-service
      - ventas-service
      - eureka-server
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-detalle-venta:5432/detalle_venta_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      PRODUCTO_SERVICE_URL: http://productos-service:8085
      VENTA_SERVICE_URL: http://ventas-service:8088
      INVENTARIO_SERVICE_URL: http://inventario-service:8090
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

  postgres-detalle-venta-test:
    image: postgres:16
    container_name: postgres-detalle-venta-test
    restart: always
    environment:
      POSTGRES_DB: detalle_venta_test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5456:5432"
    volumes:
      - postgres_detalle_venta_test_data:/var/lib/postgresql/data

  pedidos-service:
    build:
      context: ./pedidos-service
    container_name: pedidos-service
    restart: always
    depends_on:
      - postgres-pedidos
      - proveedores-service
      - eureka-server
    ports:
      - "8092:8092"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-pedidos:5432/pedidos_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      PROVEEDOR_SERVICE_URL: http://proveedores-service:8086
      PRODUCTO_SERVICE_URL: http://productos-service:8085
      CLIENTE_SERVICE_URL: http://clientes-service:8087

volumes:
  postgres_categorias_data:
  postgres_categorias_test_data:
  postgres_productos_data:
  postgres_productos_test_data:
  postgres_inventario_data:
  postgres_inventario_test_data:
  postgres_clientes_data:
  postgres_clientes_test_data:
  postgres_ventas_data:
  postgres_ventas_test_data:
  postgres_detalle_venta_data:
  postgres_detalle_venta_test_data:
  postgres_proveedores_data:
  postgres_proveedores_test_data:
  postgres_empleados_data:
  postgres_empleados_test_data:
  postgres_pedidos_data:
  postgres_pedidos_test_data:
  postgres_usuarios_data:
  postgres_usuarios_test_data:
  