spring.application.name=ventas-service
server.port=8088

# Conexion PostgreSQL TEST
spring.datasource.url=jdbc:postgresql://localhost:5463/ventas_test_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA para pruebas
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Flyway desactivado para pruebas
spring.flyway.enabled=false

# URL microservicios TEST
cliente-service.url=http://localhost:8087
detalleventa-service.url=http://localhost:8089
empleado-service.url=http://localhost:8091