spring.application.name=inventario-service
server.port=8090

# Conexion PostgreSQL TEST
spring.datasource.url=jdbc:postgresql://localhost:5458/inventario_test_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA para pruebas
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Flyway desactivado para pruebas
spring.flyway.enabled=false

# URL microservicio productos TEST
producto-service.url=http://localhost:8085