spring.application.name=empleados-service
server.port=8091

# Conexion PostgreSQL DEV
spring.datasource.url=jdbc:postgresql://postgres-empleados:5432/empleados_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# URL de microservicios
ventas-service.url=http://localhost:8088

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/